// ===== Sheet name constants =====
const VALIDATION_CHECK_SHEET_NAME = "Check";
const QUOTATION_SHEET_NAMES = {
  QUOTE: "Quote",
  TOTAL: "Total",
  TOTAL2: "Total2",
  TOTAL3: "Total3",
  SETUP: "Setup",
  REGISTRATION_1: "Registration_1",
  REGISTRATION_2: "Registration_2",
  INTERIM_1: "Interim_1",
  INTERIM_2: "Interim_2",
  OBSERVATION_1: "Observation_1",
  OBSERVATION_2: "Observation_2",
  CLOSING: "Closing",
  TRIAL: "Trial",
  ITEMS: "Items",
  QUOTATION_REQUEST: "Quotation Request",
  PRICE: "Price",
  PRICE_LOGIC_COMPANY: "PriceLogicCompany",
  PRICE_LOGIC: "PriceLogic",
};

const ORG = {
  NMC: "nmc",
  OSCR: "oscr",
};

const SHEET_PREFIX = {
  QUOTE: `${QUOTATION_SHEET_NAMES.QUOTE}_`,
  TOTAL: `${QUOTATION_SHEET_NAMES.TOTAL}_`,
  TOTAL2: `${QUOTATION_SHEET_NAMES.TOTAL2}_`,
  TOTAL3: `${QUOTATION_SHEET_NAMES.TOTAL3}_`,
};
QUOTATION_SHEET_NAMES.TOTAL_NMC = `${QUOTATION_SHEET_NAMES.TOTAL}_nmc`;
QUOTATION_SHEET_NAMES.TOTAL2_NMC = `${QUOTATION_SHEET_NAMES.TOTAL2}_nmc`;
QUOTATION_SHEET_NAMES.TOTAL_OSCR = `${QUOTATION_SHEET_NAMES.TOTAL}_oscr`;
QUOTATION_SHEET_NAMES.TOTAL2_OSCR = `${QUOTATION_SHEET_NAMES.TOTAL2}_oscr`;
QUOTATION_SHEET_NAMES.QUOTE_NMC = `${QUOTATION_SHEET_NAMES.QUOTE}_nmc`;
QUOTATION_SHEET_NAMES.QUOTE_OSCR = `${QUOTATION_SHEET_NAMES.QUOTE}_oscr`;
