const FUNCTION_FORMULAS = {
  NUMBER_OF_CASES: `=${TRIAL_SHEET.NAME}!${TRIAL_SHEET.COLNAMES.VALUE}${TRIAL_SHEET.ROWS.CASES}`,
  FACILITIES: `=${TRIAL_SHEET.NAME}!${TRIAL_SHEET.COLNAMES.VALUE}${TRIAL_SHEET.ROWS.FACILITIES}`,
};
const CDISC_ADDITION = 3;
